/* Dashboard OCHA: Vanilla JS + Canvas, no external libraries */
(function(){
  const payload = window.REGISTRY_PAYLOAD || {metadata:{}, records:[]};
  const raw = payload.records || [];
  const state = { data: raw.slice(), sortKey:'fecha_evaluacion', sortDir:'desc' };
  const $ = id => document.getElementById(id);
  const blueScale = ['#003A70','#005A99','#1F77B4','#418FDE','#5AA0E2','#8ABCEB','#B7D7F4','#D7E8FA'];
  const statusColors = { 'completado':'#418FDE', 'en curso':'#F2A900', 'planificado':'#F4B4B8' };

  function countBy(arr, getter){return arr.reduce((acc,item)=>{const key=getter(item)||'Sin dato'; acc[key]=(acc[key]||0)+1; return acc;},{});}
  function unique(arr){return [...new Set(arr.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));}
  function flatMap(arr,getter){return arr.reduce((a,x)=>a.concat(getter(x)||[]),[]);}
  function escapeHtml(str){return String(str||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function statusClass(s){s=(s||'').toLowerCase(); if(s.includes('complet'))return 'estado-completado'; if(s.includes('curso'))return 'estado-en-curso'; if(s.includes('plan'))return 'estado-planificado'; return '';}
  function statusColor(label){const s=(label||'').toLowerCase(); if(s.includes('complet')) return statusColors['completado']; if(s.includes('curso')) return statusColors['en curso']; if(s.includes('plan')) return statusColors['planificado']; return '#767676';}
  function topN(obj,n){return Object.fromEntries(Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,n));}

  function init(){
    $('lastUpdate').textContent = payload.metadata?.ultimo_registro_publicado || '—';
    $('sourceLabel').textContent = 'Registro de evaluaciones en Kobo.';
    populateFilters(); bindEvents(); render();
  }
  function populateFilters(){fillSelect('statusFilter', unique(raw.map(r=>r.estado_evaluacion))); fillSelect('sectorFilter', unique(flatMap(raw,r=>r.sectores))); fillSelect('admin1Filter', unique(flatMap(raw,r=>r.admin1))); fillSelect('orgFilter', unique(raw.map(r=>r.organizacion)));}
  function fillSelect(id,values){const el=$(id); values.forEach(v=>{const opt=document.createElement('option'); opt.value=v; opt.textContent=v; el.appendChild(opt);});}
  function bindEvents(){['searchInput','statusFilter','sectorFilter','admin1Filter','orgFilter'].forEach(id=>$(id).addEventListener('input',applyFilters)); $('resetBtn').addEventListener('click',()=>{['searchInput','statusFilter','sectorFilter','admin1Filter','orgFilter'].forEach(id=>$(id).value=''); applyFilters();}); $('exportBtn').addEventListener('click',exportFilteredCsv); document.querySelectorAll('th[data-sort]').forEach(th=>th.addEventListener('click',()=>{const key=th.dataset.sort; if(state.sortKey===key){state.sortDir=state.sortDir==='asc'?'desc':'asc';}else{state.sortKey=key;state.sortDir='asc';} renderTable(state.data);}));}
  function applyFilters(){const q=$('searchInput').value.trim().toLowerCase(); const status=$('statusFilter').value, sector=$('sectorFilter').value, admin1=$('admin1Filter').value, org=$('orgFilter').value; state.data=raw.filter(r=>{const haystack=[r.titulo,r.organizacion,r.agencia_lider,r.estado_evaluacion,r.frecuencia,r.nivel_cobertura,(r.sectores||[]).join(' '),(r.admin1||[]).join(' '),(r.admin2||[]).map(x=>x.municipio).join(' '),r.detalle_cobertura].join(' ').toLowerCase();return (!q||haystack.includes(q)) && (!status||r.estado_evaluacion===status) && (!sector||(r.sectores||[]).includes(sector)) && (!admin1||(r.admin1||[]).includes(admin1)) && (!org||r.organizacion===org);}); render();}
  function render(){renderKPIs(state.data); renderCharts(state.data); renderTable(state.data);}
  function renderKPIs(data){$('kpiTotal').textContent=data.length; $('kpiCompleted').textContent=data.filter(r=>(r.estado_evaluacion||'').toLowerCase().includes('complet')).length; $('kpiProgress').textContent=data.filter(r=>(r.estado_evaluacion||'').toLowerCase().includes('curso')).length; $('kpiOrgs').textContent=unique(data.map(r=>r.organizacion)).length; $('kpiSectors').textContent=unique(flatMap(data,r=>r.sectores)).length; $('kpiAdmin1').textContent=unique(flatMap(data,r=>r.admin1)).length; $('rowCount').textContent=`${data.length} registros`;}
  function renderCharts(data){const status=countBy(data,r=>r.estado_evaluacion); $('statusSummary').textContent=Object.entries(status).map(([k,v])=>`${k}: ${v}`).join(' · ') || 'Sin datos'; drawDonut('statusChart',status); drawHorizontalBars('sectorChart',topN(countBy(flatMap(data,r=>r.sectores).map(s=>({s})),x=>x.s),10)); drawHorizontalBars('geoChart',topN(countBy(flatMap(data,r=>r.admin1).map(s=>({s})),x=>x.s),10)); drawHorizontalBars('orgChart',topN(countBy(data,r=>r.organizacion),10));}
  function setCanvasSize(id,desiredHeight){const c=$(id); const dpr=window.devicePixelRatio||1; const rect=c.getBoundingClientRect(); const cssW=Math.max(320,rect.width); const cssH=Math.max(110,desiredHeight); c.style.height=cssH+'px'; c.width=cssW*dpr; c.height=cssH*dpr; const ctx=c.getContext('2d'); ctx.setTransform(dpr,0,0,dpr,0,0); ctx.clearRect(0,0,cssW,cssH); return {canvas:c,ctx,w:cssW,h:cssH};}
  function chartHeight(entries,type){if(type==='donut') return entries<=2 ? 150 : Math.min(230, Math.max(160, entries*30+70)); return Math.min(340, Math.max(115, entries*32+34));}
  function drawDonut(id,obj){const entries=Object.entries(obj); const total=entries.reduce((a,b)=>a+b[1],0)||1; const {ctx,w,h}=setCanvasSize(id,chartHeight(entries.length,'donut')); if(entries.length===0){drawEmpty(ctx,w,h);return;} const cx=Math.min(w*0.28,150), cy=h/2, r=Math.min(h*.36,58); let start=-Math.PI/2; entries.forEach(([label,value])=>{const a=value/total*Math.PI*2; ctx.beginPath(); ctx.moveTo(cx,cy); ctx.arc(cx,cy,r,start,start+a); ctx.closePath(); ctx.fillStyle=statusColor(label); ctx.fill(); start+=a;}); ctx.globalCompositeOperation='destination-out'; ctx.beginPath(); ctx.arc(cx,cy,r*.58,0,Math.PI*2); ctx.fill(); ctx.globalCompositeOperation='source-over'; ctx.fillStyle='#003A70'; ctx.font='700 22px Segoe UI'; ctx.textAlign='center'; ctx.textBaseline='middle'; ctx.fillText(total,cx,cy); ctx.textAlign='left'; ctx.font='12px Segoe UI'; let y=Math.max(25,(h-entries.length*23)/2+10); const lx=Math.min(w*0.56,270); entries.forEach(([label,value])=>{ctx.fillStyle=statusColor(label); ctx.fillRect(lx,y-9,11,11); ctx.fillStyle='#1F2937'; ctx.fillText(`${truncate(label,28)} (${value})`,lx+17,y-3); y+=23;});}
  function drawHorizontalBars(id,obj){const entries=Object.entries(obj); const {ctx,w,h}=setCanvasSize(id,chartHeight(entries.length,'bar')); if(entries.length===0){drawEmpty(ctx,w,h);return;} const max=Math.max(1,...entries.map(e=>e[1])); const left=Math.min(185,Math.max(125,w*.32)); const right=42; const top=14; const gap=7; const barH=Math.max(15,Math.min(22,(h-top-12)/entries.length-gap)); ctx.font='12px Segoe UI'; ctx.textBaseline='middle'; entries.forEach(([label,value],i)=>{const y=top+i*(barH+gap); const bw=Math.max(3,(w-left-right)*(value/max)); ctx.fillStyle='#EAF3FC'; ctx.fillRect(left,y,w-left-right,barH); ctx.fillStyle=blueScale[i%blueScale.length]; ctx.fillRect(left,y,bw,barH); ctx.fillStyle='#374151'; ctx.textAlign='right'; ctx.fillText(truncate(label,26),left-9,y+barH/2); ctx.textAlign='left'; ctx.fillStyle='#003A70'; ctx.font='700 12px Segoe UI'; ctx.fillText(value,left+bw+8,y+barH/2); ctx.font='12px Segoe UI';});}
  function drawEmpty(ctx,w,h){ctx.fillStyle='#767676'; ctx.textAlign='center'; ctx.font='13px Segoe UI'; ctx.fillText('Sin datos para los filtros seleccionados',w/2,h/2);}
  function truncate(s,n){s=String(s||'Sin dato'); return s.length>n?s.slice(0,n-1)+'…':s;}
  function renderTable(data){const sorted=data.slice().sort((a,b)=>{const A=(a[state.sortKey]||'').toString(),B=(b[state.sortKey]||'').toString(); const cmp=A.localeCompare(B,'es',{numeric:true}); return state.sortDir==='asc'?cmp:-cmp;}); document.querySelector('#registryTable tbody').innerHTML=sorted.map(r=>`<tr><td><strong>${escapeHtml(r.titulo||'Sin título')}</strong><br><span class="muted">${escapeHtml(r.nivel_cobertura||'')}</span></td><td>${escapeHtml(r.organizacion||'Sin dato')}<br><span class="muted">Líder: ${escapeHtml(r.agencia_lider||'Sin dato')}</span></td><td><span class="badge ${statusClass(r.estado_evaluacion)}">${escapeHtml(r.estado_evaluacion||'Sin dato')}</span></td><td>${escapeHtml(r.fecha_evaluacion||'Sin dato')}</td><td>${(r.sectores||[]).map(s=>`<span class="badge">${escapeHtml(s)}</span>`).join(' ')||'<span class="muted">Sin dato</span>'}</td><td>${(r.admin1||[]).map(s=>`<span class="badge">${escapeHtml(s)}</span>`).join(' ')||'<span class="muted">Sin dato</span>'}</td><td>${r.url_reporte?`<a class="link" target="_blank" rel="noopener" href="${escapeHtml(r.url_reporte)}">Abrir reporte</a>`:'<span class="muted">No disponible</span>'}</td></tr>`).join('');}
  function exportFilteredCsv(){const lines=[['titulo','organizacion','agencia_lider','estado_evaluacion','fecha_evaluacion','sectores','estado','tiene_reporte','url_reporte'].join(',')].concat(state.data.map(r=>[r.titulo,r.organizacion,r.agencia_lider,r.estado_evaluacion,r.fecha_evaluacion,(r.sectores||[]).join('|'),(r.admin1||[]).join('|'),r.tiene_reporte,r.url_reporte].map(csvCell).join(','))); const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='assessment_registry_filtrado.csv'; a.click(); URL.revokeObjectURL(url);}
  function csvCell(v){v=String(v??''); return '"'+v.replace(/"/g,'""')+'"';}
  let resizeTimer=null; window.addEventListener('resize',()=>{clearTimeout(resizeTimer); resizeTimer=setTimeout(()=>renderCharts(state.data),120);});
  init();
})();
